apiVersion: v1
kind: Secret
metadata:
    name: demoapp-credentials
    namespace: demoapp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:DZMELH0=,iv:XPSVq2o8fetCfmIAtN9gZgKlDDsk/3McdPtOJbsuFIM=,tag:uRFMtyU2RAYGWnddnicbZQ==,type:str]
    password: ENC[AES256_GCM,data:4Hj2LCdmcyDg0A==,iv:iVybKN7VkRh7RrXoRRH6Qg9qGolK/RwoXnvVJnfvMe8=,tag:Uup0UBy+IwMdgOqA3gKxsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://poc-cd-flux-kv.vault.azure.net
          name: sops-key
          version: 59602f7b3a8e47dea9c3fe9fe1410978
          created_at: "2021-06-21T19:22:41Z"
          enc: d08AboVWnX_EIPXbtibJg2SybvcN1P_vg1aKN8ffg5qO8aBVp6D6LLHNYhVJq1CuzWW25YHd2bQPhxCt36NU0PqB5VytpI2YD-xiUL024JD3eORlywHx0YlZeGzXkoZOClk3b1VPewQakMGSUkJEjZC4DEJa_pFKZ67PgA3M6RJWAitM3vw4OaSBUVuNtGast7AwXkfJ5-QdnOHqI8en9dyOIO4HyfYmBL9cWcqWz5eLxDY8SG1L2m_6L_BIanZc_ifAinkRdvFkIeeXCJ_8b4nhxSjElvYd7-l-8wi2dZIDbbtWUYOGN3WknFMOHaOGmcq0NxLsaEBFAFZMZf5K1w
    hc_vault: []
    age: []
    lastmodified: "2021-06-21T19:22:42Z"
    mac: ENC[AES256_GCM,data:HXlZo8wE6Z/3RxOSjxI887RupgkUQEYcSVKFtqI/RaFug8BmQliqnLtBWe9LwW+isnJf6KhnXbLFjy9705RfQHxkeGIHvkbs5kip0uEILyBSAdYjwhjz4bRSY334VqmlmwE8uEOfqlFUPKfridJ6JqL9/7LICiQNkOTyab9bPbw=,iv:oZbay4rI64rqmj61x6NlDM5LneN8CA4hH/NKM3Da35Q=,tag:xXabZ4cbXBywxmmXNDBYpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
